<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>LoginModule</name>
    <message>
        <location filename="../../../ui/login.py" line="40"/>
        <source>Connexion à Nova360Pro</source>
        <translation>Nova360Pro'ya Giriş</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="47"/>
        <source>Nom d&apos;utilisateur</source>
        <translation>Kullanıcı Adı</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="59"/>
        <source>Mot de passe</source>
        <translation>Şifre</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="71"/>
        <source>Se connecter</source>
        <translation>Giriş Yap</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="91"/>
        <source>Mot de passe oublié ?</source>
        <translation>Şifrenizi mi unuttunuz?</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="104"/>
        <source>Créer un compte</source>
        <translation>Hesap Oluştur</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="188"/>
        <source>Erreur</source>
        <translation>Hata</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="139"/>
        <source>Impossible de charger les données des utilisateurs.</source>
        <translation>Kullanıcı verileri yüklenemiyor.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="149"/>
        <source>Veuillez remplir tous les champs.</source>
        <translation>Tüm alanları doldurun.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="154"/>
        <source>Le nom d'utilisateur doit comporter au moins 3 caractères.</source>
        <translation>Kullanıcı adı en az 3 karakterden oluşmalıdır.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="161"/>
        <source>Le mot de passe doit comporter au moins 6 caractères.</source>
        <translation>Şifre en az 6 karakterden oluşmalıdır.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="182"/>
        <source>Connexion réussie</source>
        <translation>Başarıyla giriş yapıldı</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="182"/>
        <source>Bienvenue, {}!</source>
        <translation>Hoş geldiniz, {}!</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="188"/>
        <source>Nom d&apos;utilisateur ou mot de passe incorrect.</source>
        <translation>Kullanıcı adı veya şifre hatalı.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="191"/>
        <source>Avertissement</source>
        <translation>Uyarı</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="191"/>
        <source>Trop d'échecs de connexion. Veuillez réessayer plus tard.</source>
        <translation>Çok fazla giriş hatası. Lütfen daha sonra tekrar deneyin.</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="198"/>
        <source>Mot de passe oublié</source>
        <translation>Şifreyi unuttum</translation>
    </message>
    <message>
        <location filename="../../../ui/login.py" line="198"/>
        <source>Fonctionnalité non implémentée.</source>
        <translation>Fonksiyon uygulanmadı.</translation>
    </message>
</context>
</TS>
